# This file contains the configuration settings for your Redwood app.
# This file is also what makes your Redwood app a Redwood app.
# If you remove it and try to run `yarn rw dev`, you'll get an error.
#
# For the full list of options, see the "App Configuration: redwood.toml" doc:
# https://redwoodjs.com/docs/app-configuration-redwood-toml

[web]
  title = "Upsela"
  port = 8910
  host = '0.0.0.0'
  apiUrl = "/.redwood/functions" # You can customize graphql and dbauth urls individually too: see https://redwoodjs.com/docs/app-configuration-redwood-toml#api-paths
  includeEnvironmentVariables = ['WORDPRESS_USERNAME', 'WORDPRESS_PASSWORD', 'WP_BASE_URL']
[api]
  port = 8911
[browser]
  open = true
[notifications]
  versionUpdates = ["latest"]
